### ISSUE TITLE
Why StringLiterals and NumberLiterals doesn't have 8 and 9?

### ISSUE THREAD

**Issue by jason71708** [menocomp/functional-programming#1]
I have tried adding 8 and 9 to the literals, there's nothing error.
So why not have the full number of literals?

**Comment by menocomp** [comment]
Hey @jason71708 :) 
I just added numbers till 7 :) you can have string/number literals with more and more numbers if you want.

**Comment by menocomp** [comment]
Keep in mind that there is no built-in intrinsic types that can be used to increase/decrease numbers in typescript, so I had to create a fake one.
